pyroscope-io/docs

docs/developer-guide.mdx

Not really adding much, but it makes more explicit that we have a "fast" local dev flow.
It may help people that are just skimming over the docs.

suggest 'make dev' flow in a more explicit way

---

docs/developer-guide.mdx

The instructions are based on
https://github.com/pyroscope-io/pyroscope/pull/532

chore: improve dependency installation for linux in developer guide.

---

.github/workflows/smoke-tests.yml
.github/workflows/url-linter.rb
docs/agent-configuration-adhoc.mdx
docs/agent-install-windows.mdx
docs/agent-overview.mdx
docs/auth-github.mdx
docs/auth-gitlab.mdx
docs/auth-google.mdx
docs/configuration.mdx
docs/getting-started.mdx
docs/installing-pyroscope-overview.mdx
docs/integration-dotnet.mdx
docs/new-integrations.mdx
docs/retention.mdx
docs/server-install-linux.mdx
docs/server-install-macos.mdx
docs/server-overview.mdx
docs/supported-integrations.mdx
docusaurus.config.js

This fixes an issue with [trailing slashes](https://docusaurus.io/docs/api/docusaurus-config#trailing-slash) and also brings back broken links check.

Fixes docs links

---

.github/workflows/url-linter.rb
docs/agent-configuration-adhoc.mdx
docs/configuration.mdx

This is related to https://github.com/pyroscope-io/pyroscope/pull/728

feat: update docs with changes to support adhoc standalone HTML.

---

blog/profiling-go-apps-with-pyroscope.mdx

docs: Add Golang blog

---

docs/integration-golang-pull-mode.mdx

Link was out of sync. An example of how this would be easier to deal with if the docs were in the same repo :)

Fix kubernetes example link

---

docs/agent-configuration-adhoc.mdx
docs/configuration.mdx

Reflect the changes in https://github.com/pyroscope-io/pyroscope/commit/98d9a14efaf27672a6b31c63e1591f0df64d277f
Marking as a draft till the related PR is actually merged.

doc: Update adhoc docs to reflect latest changes in the command.

---

docs/auth-overview.mdx
docs/integration-golang.mdx
docs/integration-java.mdx
docs/integration-python.mdx
docs/integration-ruby.mdx
docs/server-api-reference.mdx

The PR documents how to enable agent authentication and authenticate API clients

Add documentation for agent authentication

---

docs/integration-golang-pull-mode.mdx

👋🏼 hi team,
Just fixing a broken URL

fix: update example doc links

---

blog/what-is-continuous profiling.mdx
blog/what-is-continuous-profiling.mdx
package.json
src/theme/BlogPostItem/index.js
yarn.lock

New blog: what is continuous profiling?

---

blog/what-is-continuous-profiling.mdx

Chore: add Kat as a co-author to blog

---

docs/integration-rust.mdx

Chore: fix flaky CI

---

blog/what-is-a-flamegraph.mdx

New blog: what is a flamegraph?

---

docs/remote-write.mdx

docs: add remote-write diagram

---

docs/integration-python.mdx

This could benefit from some editing/review.

docs: update Python docs

---

docs/developer-guide.mdx

docs:add goland guide

---

docs/integration-golang-pull-mode.mdx
docs/integration-golang.mdx

docs: add "pyroscope.ProfileGoroutines" known risk on the go client page #99

---

docs/supported-integrations.mdx

Adds rust / java to supported languages

Add Rust/Java to supported languages

---

docs/installing-pyroscope-overview.mdx

The list was not full so it made me confused about Pyroscope not having java integration.
I have also reordered elements as they are ordered in a sidebar.

Added new integrations to the list in overview

---

blog/how-to-profile-lambda-functions.mdx

docs: adds lambda function profiling blog post

---

docs/integration-golang-tracing.mdx
docs/integration-java-tracing.mdx

Updates otel tracing links and images

update otel tracing links / images

---

src/components/Homepage/WhatTheySay/index.jsx
src/components/Homepage/WhatTheySay/styles.module.scss

Add more tweets to community section

---

docs/integration-ebpf.mdx

WIP until https://github.com/pyroscope-io/helm-chart/pull/80 is merged

improve ebpf docs

---

docs/integration-dotnet.mdx

See https://github.com/pyroscope-io/pyroscope/pull/1492

Update list of supported dotnet versions

---

docs/integration-ebpf.mdx

Fixes https://github.com/pyroscope-io/docs/issues/126
thanks @Jun10ng

Fix link in eBPF docs

---

.github/workflows/deploy.yml

Same thing as https://github.com/pyroscope-io/pyroscope/pull/1594

skip deploy step if DOCS_PRIVATE_ACCESS_TOKEN is not available

---

docs/integration-dotnet.mdx

Related: https://github.com/pyroscope-io/pyroscope/pull/1622

docs: remove SYS_PTRACE from dotnetspy examples

---

docs/integration-golang-pull-mode.mdx

Updates service discovery docs to not link to prometheus but rather show our own version

docs: update service discovery docs

---

package.json
yarn.lock

- https://github.com/pyroscope-io/pyroscope/issues/1611
- upgrading flamegraph version solves problem with react-menu library

fix: upgrade flamegraph version

---

blog/introducing-sandwich-view.mdx
src/components/Blog/ImageSwitcher.jsx

Add blog introducing sandwich view

---

docs/integration-golang-pull-mode.mdx

Depends on https://github.com/pyroscope-io/pyroscope/pull/1865

docs: add consul service discovery

---

docusaurus.config.js
src/components/Homepage/index.jsx
src/theme/AnnouncementBar/styles.module.css

Adding announcement about some exciting news to the website!

Add Grafana announcement to website

---

docs/remote-write.mdx

https://github.com/pyroscope-io/docs/issues/165

docs: remote write to phlare example

---

blog/grafana-cloud-profiles-pyroscope.mdx

Add grafana cloud blog post

---

src/javaCodeBlocks.js

Super tiny typo fix
